/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.projecttemplate;

import java.awt.event.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.*;
import java.util.*;
import javax.swing.*;



/**
 *
 * @author Admin
 */
public class Book1 extends javax.swing.JInternalFrame {
    
    private String bookid;
    /**
     * Creates new form Book1
     */
    public Book1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdoGroupDay = new javax.swing.ButtonGroup();
        rdoGroupMember = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        rdo30day = new javax.swing.JRadioButton();
        btnAddtocart = new javax.swing.JButton();
        imageBook = new javax.swing.JLabel();
        labelBookName = new javax.swing.JLabel();
        txtDay = new javax.swing.JLabel();
        rdo1day = new javax.swing.JRadioButton();
        rdo7day = new javax.swing.JRadioButton();
        rdo3day = new javax.swing.JRadioButton();
        rdo60day = new javax.swing.JRadioButton();
        rdo15day = new javax.swing.JRadioButton();
        btnGoBack = new javax.swing.JButton();
        labelAuthorName = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1440, 800));

        rdoGroupDay.add(rdo30day);
        rdo30day.setText("30 day");

        btnAddtocart.setBackground(new java.awt.Color(255, 153, 204));
        btnAddtocart.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAddtocart.setForeground(new java.awt.Color(255, 255, 255));
        btnAddtocart.setText("+ Add to cart");
        btnAddtocart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddtocartMouseClicked(evt);
            }
        });

        imageBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageBook.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelBookName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelBookName.setText("Book Name");

        txtDay.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtDay.setText("Day");

        rdoGroupDay.add(rdo1day);
        rdo1day.setText("1 day");

        rdoGroupDay.add(rdo7day);
        rdo7day.setText("7 day");

        rdoGroupDay.add(rdo3day);
        rdo3day.setText("3 day");

        rdoGroupDay.add(rdo60day);
        rdo60day.setText("60 day");

        rdoGroupDay.add(rdo15day);
        rdo15day.setText("15 day");

        btnGoBack.setText("Go Back");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        labelAuthorName.setText("jLabel1");

        jDesktopPane1.setLayer(rdo30day, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnAddtocart, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(imageBook, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(labelBookName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtDay, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(rdo1day, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(rdo7day, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(rdo3day, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(rdo60day, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(rdo15day, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnGoBack, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(labelAuthorName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGoBack))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(imageBook, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelAuthorName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(rdo30day)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdo60day))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdo1day)
                                            .addComponent(rdo7day)
                                            .addComponent(txtDay))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdo3day)
                                            .addComponent(rdo15day))))
                                .addGap(394, 394, 394)))))
                .addContainerGap(174, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(735, 735, 735)
                    .addComponent(labelBookName)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                    .addComponent(btnAddtocart, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(89, 89, 89)))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGoBack)
                        .addGap(18, 18, 18)
                        .addComponent(imageBook, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(labelAuthorName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdo3day, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rdo1day, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdo15day)
                            .addComponent(rdo7day))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdo30day)
                            .addComponent(rdo60day))
                        .addGap(263, 263, 263)))
                .addContainerGap(203, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelBookName)
                        .addComponent(btnAddtocart, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(537, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    
    public void setBookDetails(String bookid,String bookName, String author,String picUrl) {
        labelBookName.setText(bookName);
        labelAuthorName.setText(author);
        
        ImageIcon newIcon = new ImageIcon(picUrl);
        imageBook.setIcon(newIcon);
        this.bookid = bookid;
    }
        
    
    //back to store
    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        Explore1 exP = new Explore1();
        exP.setVisible(true);
        desktop.add(exP);

    }//GEN-LAST:event_btnGoBackActionPerformed
    //add to cart btn
    private void btnAddtocartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddtocartMouseClicked
        // Assuming you have a user identifier or session
    String userId = Globalinfo.username;

    // Get the current ownedbooks value from the database
    String currentOwnedBooks = getOwnedBooksFromDatabase(userId);

    // Assuming bookId is the ID of the book you want to add to the cart
    String bookId = bookid;  // Replace with your actual book ID

    // Get the selected rent day from the radio buttons
    String rentDay = getSelectedRentDay();
    
    

    // Append the new book ID and rent day to the existing ownedbooks value
    String updatedOwnedBooks = appendBookInfo(currentOwnedBooks, bookId, rentDay);

    // Update the database with the modified ownedbooks value
    updateOwnedBooksInDatabase(userId, updatedOwnedBooks);
    
    JOptionPane.showMessageDialog(null, "Add to cart successfully");
    }//GEN-LAST:event_btnAddtocartMouseClicked
    ///////
    
    
    // Method to get the selected rent day from the radio buttons
private String getSelectedRentDay() {
    if (rdo1day.isSelected()) {
        return "1 day";
    } else if (rdo3day.isSelected()) {
        return "3 days";
    } else if (rdo7day.isSelected()) {
        return "7 days";
    } else if (rdo15day.isSelected()) {
        return "15 days";
    } else if (rdo30day.isSelected()) {
        return "30 days";
    } else if (rdo60day.isSelected()) {
        return "60 days";
    } else {
        // Handle the case where no radio button is selected
        return "";
    }
}

// Method to append book ID and rent day to the existing ownedbooks value
private String appendBookInfo(String currentOwnedBooks, String newBookId, String rentDay) {
    String bookInfo = newBookId + "(" + rentDay + ")";

    if (currentOwnedBooks == null || currentOwnedBooks.isEmpty()) {
        return bookInfo;
    } else {
        // Check if the new book ID already exists in the list
        if (!currentOwnedBooks.contains(newBookId)) {
            return currentOwnedBooks + "," + bookInfo;
        } else {
            // Handle the case where the book ID already exists
            // You can choose to skip adding it again or handle it differently
            return currentOwnedBooks;
        }
    }
}

private String getOwnedBooksFromDatabase(String userId) {
    // Use your DatabaseManager class to get the value from the database
    // Implement the necessary logic to retrieve the ownedbooks value for the given user
    // ...

    try (Connection connection = DatabaseManager.getConnection()) {
        String query = "SELECT ownedbook FROM accountList WHERE username = ?";
        try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setString(1, userId);
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    return resultSet.getString("ownedbook");
                }
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
        // Handle the exception appropriately, e.g., log or display an error message
    }

    // Return an empty string if no value is found
    return "";
}

// Helper method to update the ownedbooks value in the database
private void updateOwnedBooksInDatabase(String userId, String updatedOwnedBooks) {
    try (Connection connection = DatabaseManager.getConnection()) {
        String query = "UPDATE accountList SET ownedbook = ? WHERE username = ?";
        try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
            preparedStatement.setString(1, updatedOwnedBooks);
            preparedStatement.setString(2, userId);
            preparedStatement.executeUpdate();
        }
    } catch (SQLException e) {
        e.printStackTrace();
        // Handle the exception appropriately, e.g., log or display an error message
    }
}


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddtocart;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JLabel imageBook;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel labelAuthorName;
    private javax.swing.JLabel labelBookName;
    private javax.swing.JRadioButton rdo15day;
    private javax.swing.JRadioButton rdo1day;
    private javax.swing.JRadioButton rdo30day;
    private javax.swing.JRadioButton rdo3day;
    private javax.swing.JRadioButton rdo60day;
    private javax.swing.JRadioButton rdo7day;
    private javax.swing.ButtonGroup rdoGroupDay;
    private javax.swing.ButtonGroup rdoGroupMember;
    private javax.swing.JLabel txtDay;
    // End of variables declaration//GEN-END:variables
}
