/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.projecttemplate;

import javax.swing.*;



/**
 *
 * @author Admin
 */
public class Category1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Category1
     */
    public Category1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        txtCategory = new javax.swing.JLabel();
        btnRomCom = new javax.swing.JButton();
        btnHorror = new javax.swing.JButton();
        btnMore = new javax.swing.JButton();
        btnLifeStyle1 = new javax.swing.JButton();

        setBorder(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtCategory.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        txtCategory.setText("Category");

        btnRomCom.setBackground(new java.awt.Color(255, 255, 255));
        btnRomCom.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRomCom.setText("RomCom");
        btnRomCom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnRomCom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRomComMouseClicked(evt);
            }
        });

        btnHorror.setBackground(new java.awt.Color(255, 255, 255));
        btnHorror.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnHorror.setText("Horror");
        btnHorror.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnHorror.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHorrorMouseClicked(evt);
            }
        });

        btnMore.setBackground(new java.awt.Color(255, 255, 255));
        btnMore.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnMore.setText("More");
        btnMore.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnMore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMoreMouseClicked(evt);
            }
        });

        btnLifeStyle1.setBackground(new java.awt.Color(255, 255, 255));
        btnLifeStyle1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnLifeStyle1.setText("Life Style");
        btnLifeStyle1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnLifeStyle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLifeStyle1MouseClicked(evt);
            }
        });

        jDesktopPane1.setLayer(txtCategory, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnRomCom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnHorror, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnMore, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnLifeStyle1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btnLifeStyle1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnRomCom, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnHorror, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnMore, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(615, 615, 615)
                        .addComponent(txtCategory)))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(txtCategory)
                .addGap(150, 150, 150)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRomCom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHorror, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMore, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLifeStyle1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(333, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jDesktopPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLifeStyle1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLifeStyle1MouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        LSpage lsP = new LSpage();
        lsP.setVisible(true);
        desktop.add(lsP);
    }//GEN-LAST:event_btnLifeStyle1MouseClicked

    private void btnRomComMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRomComMouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        RMpage rmP = new RMpage();
        rmP.setVisible(true);
        desktop.add(rmP);
    }//GEN-LAST:event_btnRomComMouseClicked

    private void btnHorrorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHorrorMouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        HRpage hrP = new HRpage();
        hrP.setVisible(true);
        desktop.add(hrP);
    }//GEN-LAST:event_btnHorrorMouseClicked

    private void btnMoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMoreMouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        MorePage morePage = new MorePage();
        morePage.setVisible(true);
        desktop.add(morePage);
    }//GEN-LAST:event_btnMoreMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHorror;
    private javax.swing.JButton btnLifeStyle1;
    private javax.swing.JButton btnMore;
    private javax.swing.JButton btnRomCom;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtCategory;
    // End of variables declaration//GEN-END:variables
}
