/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.projecttemplate;

import javax.swing.*;



/**
 *
 * @author Admin
 */
public class Explore1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Explore1
     */
    public Explore1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNew = new javax.swing.JLabel();
        txtRecommended = new javax.swing.JLabel();
        btnRCMBook1 = new javax.swing.JButton();
        btnRCMBook5 = new javax.swing.JButton();
        btnRCMBook6 = new javax.swing.JButton();
        btnRCMBook7 = new javax.swing.JButton();
        btnRCMBook8 = new javax.swing.JButton();
        btnRCMBook9 = new javax.swing.JButton();
        btnRCMBook10 = new javax.swing.JButton();
        btnRCMBook11 = new javax.swing.JButton();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1440, 800));

        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1440, 800));

        jLabel15.setText("Vintage Rolex");

        jLabel16.setText("The Raven");

        jLabel1.setText("Taylor Swift:A Little Golden Book");

        jLabel17.setText("BG3 complete guide");

        jLabel18.setText("Cook with Kids");

        jLabel2.setText("Beyonce:A little Golden Book");

        jLabel3.setText("The Story of Selena Quintanilla");

        jLabel4.setText("Color the Eras A Music Lover");

        txtNew.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtNew.setText("New arrival");

        txtRecommended.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtRecommended.setText("Recommended For You");

        btnRCMBook1.setBackground(new java.awt.Color(255, 255, 255));
        btnRCMBook1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taylorbook.png"))); // NOI18N
        btnRCMBook1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRCMBook1MouseClicked(evt);
            }
        });

        btnRCMBook5.setBackground(new java.awt.Color(255, 255, 255));
        btnRCMBook5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SvintageRolex.png"))); // NOI18N
        btnRCMBook5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRCMBook5MouseClicked(evt);
            }
        });

        btnRCMBook6.setBackground(new java.awt.Color(255, 255, 255));
        btnRCMBook6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beyoncebook.png"))); // NOI18N
        btnRCMBook6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRCMBook6MouseClicked(evt);
            }
        });

        btnRCMBook7.setBackground(new java.awt.Color(255, 255, 255));
        btnRCMBook7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StheRaven.png"))); // NOI18N
        btnRCMBook7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRCMBook7MouseClicked(evt);
            }
        });

        btnRCMBook8.setBackground(new java.awt.Color(255, 255, 255));
        btnRCMBook8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/selenabook.png"))); // NOI18N
        btnRCMBook8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRCMBook8MouseClicked(evt);
            }
        });

        btnRCMBook9.setBackground(new java.awt.Color(255, 255, 255));
        btnRCMBook9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sBG.png"))); // NOI18N
        btnRCMBook9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRCMBook9MouseClicked(evt);
            }
        });

        btnRCMBook10.setBackground(new java.awt.Color(255, 255, 255));
        btnRCMBook10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theErasbook.png"))); // NOI18N
        btnRCMBook10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRCMBook10MouseClicked(evt);
            }
        });

        btnRCMBook11.setBackground(new java.awt.Color(255, 255, 255));
        btnRCMBook11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScookWKid.png"))); // NOI18N
        btnRCMBook11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRCMBook11MouseClicked(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtNew, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtRecommended, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnRCMBook1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnRCMBook5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnRCMBook6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnRCMBook7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnRCMBook8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnRCMBook9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnRCMBook10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnRCMBook11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRecommended)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNew)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnRCMBook5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRCMBook1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(95, 95, 95)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnRCMBook7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(btnRCMBook6)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(95, 95, 95)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(btnRCMBook8)
                            .addComponent(btnRCMBook9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(97, 97, 97)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnRCMBook11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(btnRCMBook10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(txtRecommended)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRCMBook1)
                    .addComponent(btnRCMBook6)
                    .addComponent(btnRCMBook8)
                    .addComponent(btnRCMBook10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(72, 72, 72)
                .addComponent(txtNew)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRCMBook7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRCMBook9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRCMBook5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(17, 17, 17)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(btnRCMBook11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1464, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1464, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRCMBook1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRCMBook1MouseClicked
        // TODO add your handling code here:
        
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        String bookId = "001";  // Set the actual book ID
        String bookName = DatabaseManager.getBookNameById(bookId);
        String author = DatabaseManager.getAuthorById(bookId);
        String picURL = "src\\main\\resources\\rec1.png";
        
        Book1 bookP = new Book1();
        bookP.setBookDetails(bookId,bookName,author,picURL);
        bookP.setVisible(true);
        desktop.add(bookP);
    }//GEN-LAST:event_btnRCMBook1MouseClicked

    private void btnRCMBook6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRCMBook6MouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        String bookId = "002";  // Set the actual book ID
        String bookName = DatabaseManager.getBookNameById(bookId);
        String author = DatabaseManager.getAuthorById(bookId);
        String picURL = "src\\main\\resources\\rec2.png";
        
        Book1 bookP = new Book1();
        bookP.setBookDetails(bookId,bookName,author,picURL);
        bookP.setVisible(true);
        desktop.add(bookP);
    }//GEN-LAST:event_btnRCMBook6MouseClicked

    private void btnRCMBook8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRCMBook8MouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        String bookId = "003";  // Set the actual book ID
        String bookName = DatabaseManager.getBookNameById(bookId);
        String author = DatabaseManager.getAuthorById(bookId);
        String picURL = "src\\main\\resources\\rec3.png";
        
        Book1 bookP = new Book1();
        bookP.setBookDetails(bookId,bookName,author,picURL); 
        bookP.setVisible(true);
        desktop.add(bookP);
    }//GEN-LAST:event_btnRCMBook8MouseClicked

    private void btnRCMBook10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRCMBook10MouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        String bookId = "004";  // Set the actual book ID
        String bookName = DatabaseManager.getBookNameById(bookId);
        String author = DatabaseManager.getAuthorById(bookId);
        String picURL = "src\\main\\resources\\rec4.png";
        
        Book1 bookP = new Book1();
        bookP.setBookDetails(bookId,bookName,author,picURL);
        bookP.setVisible(true);
        desktop.add(bookP);
    }//GEN-LAST:event_btnRCMBook10MouseClicked

    private void btnRCMBook5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRCMBook5MouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        String bookId = "011";  // Set the actual book ID
        String bookName = DatabaseManager.getBookNameById(bookId);
        String author = DatabaseManager.getAuthorById(bookId);
        String picURL = "src\\main\\resources\\vintageRolex.png";
        
        Book1 bookP = new Book1();
        bookP.setBookDetails(bookId,bookName,author,picURL); 
        bookP.setVisible(true);
        desktop.add(bookP);
    }//GEN-LAST:event_btnRCMBook5MouseClicked

    private void btnRCMBook7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRCMBook7MouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        String bookId = "016";  // Set the actual book ID
        String bookName = DatabaseManager.getBookNameById(bookId);
        String author = DatabaseManager.getAuthorById(bookId);
        String picURL = "src\\main\\resources\\theRaven.png";
        
        Book1 bookP = new Book1();
        bookP.setBookDetails(bookId,bookName,author,picURL); 
        bookP.setVisible(true);
        desktop.add(bookP);
    }//GEN-LAST:event_btnRCMBook7MouseClicked

    private void btnRCMBook9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRCMBook9MouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        String bookId = "013";  // Set the actual book ID
        String bookName = DatabaseManager.getBookNameById(bookId);
        String author = DatabaseManager.getAuthorById(bookId);
        String picURL = "src\\main\\resources\\BG.png";
        
        Book1 bookP = new Book1();
        bookP.setBookDetails(bookId,bookName,author,picURL); 
        bookP.setVisible(true);
        desktop.add(bookP);
    }//GEN-LAST:event_btnRCMBook9MouseClicked

    private void btnRCMBook11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRCMBook11MouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        String bookId = "010";  // Set the actual book ID
        String bookName = DatabaseManager.getBookNameById(bookId);
        String author = DatabaseManager.getAuthorById(bookId);
        String picURL = "src\\main\\resources\\cookWKid.png";
        
        Book1 bookP = new Book1();
        bookP.setBookDetails(bookId,bookName,author,picURL);
        bookP.setVisible(true);
        desktop.add(bookP);
    }//GEN-LAST:event_btnRCMBook11MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRCMBook1;
    private javax.swing.JButton btnRCMBook10;
    private javax.swing.JButton btnRCMBook11;
    private javax.swing.JButton btnRCMBook5;
    private javax.swing.JButton btnRCMBook6;
    private javax.swing.JButton btnRCMBook7;
    private javax.swing.JButton btnRCMBook8;
    private javax.swing.JButton btnRCMBook9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtNew;
    private javax.swing.JLabel txtRecommended;
    // End of variables declaration//GEN-END:variables
}
