/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.projecttemplate;

import javax.swing.*;

/**
 *
 * @author Lenovo
 */
public class Home extends javax.swing.JInternalFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        btnRecommend4 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        btnExploreinHomePage2 = new javax.swing.JLabel();
        homePic = new javax.swing.JLabel();
        btnGoToExplore = new javax.swing.JLabel();
        btnRecommend2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnReccommend1 = new javax.swing.JLabel();
        btnRecommend3 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCatLifeStyle = new javax.swing.JLabel();
        btnCatRomCom = new javax.swing.JLabel();
        btnCatHorror = new javax.swing.JLabel();
        btnCatMore = new javax.swing.JLabel();
        btnRecommend6 = new javax.swing.JLabel();
        btnRecommend5 = new javax.swing.JLabel();
        btnRecommend8 = new javax.swing.JLabel();
        btnRecommend7 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1440, 700));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(16);

        jPanel3.setPreferredSize(new java.awt.Dimension(1440, 1930));

        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnRecommend4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRecommend4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theErasbook.png"))); // NOI18N
        btnRecommend4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRecommend4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecommend4MouseClicked(evt);
            }
        });

        jLayeredPane3.setBackground(new java.awt.Color(255, 204, 204));

        jLabel39.setFont(new java.awt.Font("Verdana", 1, 45)); // NOI18N
        jLabel39.setText("Welcome to Book Heaven!");

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel40.setText("Discover the world through words at Book Haven ");

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel41.setText("- where stories come alive, minds find refuge, and knowledge blooms.");

        homePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ant-design_picture-filled.png"))); // NOI18N

        btnGoToExplore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGoToExplore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonExplore.png"))); // NOI18N
        btnGoToExplore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGoToExploreMouseClicked(evt);
            }
        });

        jLayeredPane3.setLayer(jLabel39, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel40, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel41, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel42, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(btnExploreinHomePage2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(homePic, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(btnGoToExplore, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41)
                            .addComponent(jLabel39)))
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(btnExploreinHomePage2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGoToExplore)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homePic, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(269, 269, 269)
                .addComponent(jLabel42)
                .addGap(127, 127, 127))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(homePic, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(176, Short.MAX_VALUE))
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel41)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(btnExploreinHomePage2))
                            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(btnGoToExplore)))
                        .addGap(176, 176, 176))))
        );

        btnRecommend2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRecommend2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beyoncebook.png"))); // NOI18N
        btnRecommend2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRecommend2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecommend2MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        jLabel5.setText("Recommended ");

        btnReccommend1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReccommend1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taylorbook.png"))); // NOI18N
        btnReccommend1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnReccommend1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReccommend1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReccommend1MouseClicked(evt);
            }
        });

        btnRecommend3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRecommend3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/selenabook.png"))); // NOI18N
        btnRecommend3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRecommend3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecommend3MouseClicked(evt);
            }
        });

        txtSearch.setText("Welcome!! to our heaven of book the place where you can tour the knowledge.");
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Taylor Swift: A Little Golden Book ");

        jLabel8.setText("Beyonce: A Little Golden Book ");

        jLabel10.setText("The Story of Selena Quintanilla");

        jLabel12.setText("Color the Eras A Music Lover");

        jLabel23.setText("How to Catch a Unicorn");

        jLabel25.setText("The Hurricane Wars: A Novel");

        jLabel27.setText("Storm and Fury");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        jLabel7.setText("Book by category");

        btnCatLifeStyle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnCatLifeStyle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCatLifeStyle.setText("Life Style");
        btnCatLifeStyle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCatLifeStyle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCatLifeStyleMouseClicked(evt);
            }
        });

        btnCatRomCom.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnCatRomCom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCatRomCom.setText("Romcom");
        btnCatRomCom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCatRomCom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCatRomComMouseClicked(evt);
            }
        });

        btnCatHorror.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnCatHorror.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCatHorror.setText("Horror");
        btnCatHorror.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCatHorror.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCatHorrorMouseClicked(evt);
            }
        });

        btnCatMore.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnCatMore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCatMore.setText("More");
        btnCatMore.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCatMore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCatMoreMouseClicked(evt);
            }
        });

        btnRecommend6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRecommend6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lfbook.png"))); // NOI18N
        btnRecommend6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRecommend6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRecommend6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecommend6MouseClicked(evt);
            }
        });

        btnRecommend5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRecommend5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unicornbook.png"))); // NOI18N
        btnRecommend5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRecommend5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRecommend5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecommend5MouseClicked(evt);
            }
        });

        btnRecommend8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRecommend8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imobiouslybook.png"))); // NOI18N
        btnRecommend8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRecommend8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRecommend8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecommend8MouseClicked(evt);
            }
        });

        btnRecommend7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRecommend7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stormbook.png"))); // NOI18N
        btnRecommend7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRecommend7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRecommend7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecommend7MouseClicked(evt);
            }
        });

        jLabel45.setText("Imogen, Obviously");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnCatLifeStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(btnCatRomCom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(btnCatHorror, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(btnCatMore, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(554, 554, 554)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 1401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRecommend5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReccommend1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel23))
                        .addGap(107, 107, 107)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnRecommend2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnRecommend6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(btnRecommend3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(129, 129, 129)
                                .addComponent(btnRecommend4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnRecommend7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(129, 129, 129)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRecommend8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(176, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLayeredPane3)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(837, 837, 837)
                                    .addComponent(jLabel36)
                                    .addGap(397, 397, 397)
                                    .addComponent(jLabel21)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addContainerGap()))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 678, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(65, 65, 65)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnRecommend3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addGap(49, 49, 49)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRecommend7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRecommend8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnRecommend4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnRecommend5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel27)
                            .addComponent(jLabel45)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReccommend1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRecommend2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(49, 49, 49)
                        .addComponent(btnRecommend6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCatMore, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCatRomCom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCatHorror, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCatLifeStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(156, 156, 156))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(628, 628, 628)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(141, 141, 141)
                    .addComponent(jLabel7)
                    .addGap(405, 405, 405)))
        );

        jScrollPane2.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReccommend1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReccommend1MouseClicked
        // TODO add your handling code here:
        
        
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        
        String bookId = "001";  // Set the actual book ID
        String bookName = DatabaseManager.getBookNameById(bookId);
        String author = DatabaseManager.getAuthorById(bookId);
        String picURL = "src\\main\\resources\\rec1.png";
        
        Book1 bookP = new Book1();
        bookP.setBookDetails(bookId,bookName,author,picURL); 
        bookP.setVisible(true);
        desktop.add(bookP);
        
        
        
        
    }//GEN-LAST:event_btnReccommend1MouseClicked

    private void btnRecommend2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecommend2MouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        String bookId = "002";  // Set the actual book ID
        String bookName = DatabaseManager.getBookNameById(bookId);
        String author = DatabaseManager.getAuthorById(bookId);
        String picURL = "src\\main\\resources\\rec2.png";
        
        Book1 bookP = new Book1();
        bookP.setBookDetails(bookId,bookName,author,picURL); 
        bookP.setVisible(true);
        desktop.add(bookP);
    }//GEN-LAST:event_btnRecommend2MouseClicked

    private void btnRecommend3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecommend3MouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        String bookId = "003";  // Set the actual book ID
        String bookName = DatabaseManager.getBookNameById(bookId);
        String author = DatabaseManager.getAuthorById(bookId);
        String picURL = "src\\main\\resources\\rec3.png";
        
        Book1 bookP = new Book1();
        bookP.setBookDetails(bookId,bookName,author,picURL); 
        bookP.setVisible(true);
        desktop.add(bookP);
    }//GEN-LAST:event_btnRecommend3MouseClicked

    private void btnRecommend4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecommend4MouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        String bookId = "004";  // Set the actual book ID
        String bookName = DatabaseManager.getBookNameById(bookId);
        String author = DatabaseManager.getAuthorById(bookId);
        String picURL = "src\\main\\resources\\rec4.png";
        
        Book1 bookP = new Book1();
        bookP.setBookDetails(bookId,bookName,author,picURL); 
        bookP.setVisible(true);
        desktop.add(bookP);
    }//GEN-LAST:event_btnRecommend4MouseClicked

    private void btnRecommend5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecommend5MouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        String bookId = "005";  // Set the actual book ID
        String bookName = DatabaseManager.getBookNameById(bookId);
        String author = DatabaseManager.getAuthorById(bookId);
        String picURL = "src\\main\\resources\\rec5.png";
        
        Book1 bookP = new Book1();
        bookP.setBookDetails(bookId,bookName,author,picURL); 
        bookP.setVisible(true);
        desktop.add(bookP);
    }//GEN-LAST:event_btnRecommend5MouseClicked

    private void btnRecommend6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecommend6MouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        String bookId = "006";  // Set the actual book ID
        String bookName = DatabaseManager.getBookNameById(bookId);
        String author = DatabaseManager.getAuthorById(bookId);
        String picURL = "src\\main\\resources\\rec6.png";
        
        Book1 bookP = new Book1();
        bookP.setBookDetails(bookId,bookName,author,picURL); 
        bookP.setVisible(true);
        desktop.add(bookP);
    }//GEN-LAST:event_btnRecommend6MouseClicked

    private void btnRecommend7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecommend7MouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        String bookId = "007";  // Set the actual book ID
        String bookName = DatabaseManager.getBookNameById(bookId);
        String author = DatabaseManager.getAuthorById(bookId);
        String picURL = "src\\main\\resources\\rec7.png";
        
        Book1 bookP = new Book1();
        bookP.setBookDetails(bookId,bookName,author,picURL); 
        bookP.setVisible(true);
        desktop.add(bookP);
    }//GEN-LAST:event_btnRecommend7MouseClicked

    private void btnRecommend8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecommend8MouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        String bookId = "008";  // Set the actual book ID
        String bookName = DatabaseManager.getBookNameById(bookId);
        String author = DatabaseManager.getAuthorById(bookId);
        String picURL = "src\\main\\resources\\rec8.png";
        
        Book1 bookP = new Book1();
        bookP.setBookDetails(bookId,bookName,author,picURL); 
        bookP.setVisible(true);
        desktop.add(bookP);
    }//GEN-LAST:event_btnRecommend8MouseClicked

    private void btnCatLifeStyleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCatLifeStyleMouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        LSpage lsP = new LSpage();
        lsP.setVisible(true);
        desktop.add(lsP);
    }//GEN-LAST:event_btnCatLifeStyleMouseClicked

    private void btnCatRomComMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCatRomComMouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        RMpage rmP = new RMpage();
        rmP.setVisible(true);
        desktop.add(rmP);
    }//GEN-LAST:event_btnCatRomComMouseClicked

    private void btnCatHorrorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCatHorrorMouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        HRpage hrP = new HRpage();
        hrP.setVisible(true);
        desktop.add(hrP);
    }//GEN-LAST:event_btnCatHorrorMouseClicked

    private void btnCatMoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCatMoreMouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        MorePage moreP = new MorePage();
        moreP.setVisible(true);
        desktop.add(moreP);
    }//GEN-LAST:event_btnCatMoreMouseClicked

    private void btnGoToExploreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGoToExploreMouseClicked
        // TODO add your handling code here:
        
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        Explore1 epPage = new Explore1();
        epPage.setVisible(true);
        desktop.add(epPage);
    }//GEN-LAST:event_btnGoToExploreMouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCatHorror;
    private javax.swing.JLabel btnCatLifeStyle;
    private javax.swing.JLabel btnCatMore;
    private javax.swing.JLabel btnCatRomCom;
    private javax.swing.JLabel btnExploreinHomePage2;
    private javax.swing.JLabel btnGoToExplore;
    private javax.swing.JLabel btnReccommend1;
    private javax.swing.JLabel btnRecommend2;
    private javax.swing.JLabel btnRecommend3;
    private javax.swing.JLabel btnRecommend4;
    private javax.swing.JLabel btnRecommend5;
    private javax.swing.JLabel btnRecommend6;
    private javax.swing.JLabel btnRecommend7;
    private javax.swing.JLabel btnRecommend8;
    private javax.swing.JLabel homePic;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
