/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.projecttemplate;

import javax.swing.*;

/**
 *
 * @author Lenovo
 */
public class LSpage extends javax.swing.JInternalFrame {

    /**
     * Creates new form LSpage
     */
    public LSpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRCMBook1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRCMBook6 = new javax.swing.JButton();
        btnRCMBook8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRCMBook10 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1450, 800));

        btnRCMBook1.setBackground(new java.awt.Color(255, 255, 255));
        btnRCMBook1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taylorbook.png"))); // NOI18N
        btnRCMBook1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRCMBook1MouseClicked(evt);
            }
        });

        jLabel1.setText("Taylor Swift:A Little Golden Book");

        jLabel2.setText("Beyonce:A little Golden Book");

        btnRCMBook6.setBackground(new java.awt.Color(255, 255, 255));
        btnRCMBook6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beyoncebook.png"))); // NOI18N
        btnRCMBook6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRCMBook6MouseClicked(evt);
            }
        });

        btnRCMBook8.setBackground(new java.awt.Color(255, 255, 255));
        btnRCMBook8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SvintageRolex.png"))); // NOI18N
        btnRCMBook8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRCMBook8MouseClicked(evt);
            }
        });

        jLabel3.setText("Vintage Rolex");

        jLabel4.setText("Cooking with Kids");

        btnRCMBook10.setBackground(new java.awt.Color(255, 255, 255));
        btnRCMBook10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ScookWKid.png"))); // NOI18N
        btnRCMBook10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRCMBook10MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("Life Style");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(650, 650, 650)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRCMBook1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(btnRCMBook6))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(btnRCMBook8))
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRCMBook10, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel5)
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRCMBook1)
                    .addComponent(btnRCMBook6)
                    .addComponent(btnRCMBook8)
                    .addComponent(btnRCMBook10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRCMBook1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRCMBook1MouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        String bookId = "001";  // Set the actual book ID
        String bookName = DatabaseManager.getBookNameById(bookId);
        String author = DatabaseManager.getAuthorById(bookId);
        String picURL = "src\\main\\resources\\rec1.png";
        
        Book1 bookP = new Book1();
        bookP.setBookDetails(bookId,bookName,author,picURL); 
        bookP.setVisible(true);
        desktop.add(bookP);
    }//GEN-LAST:event_btnRCMBook1MouseClicked

    private void btnRCMBook6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRCMBook6MouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        String bookId = "002";  // Set the actual book ID
        String bookName = DatabaseManager.getBookNameById(bookId);
        String author = DatabaseManager.getAuthorById(bookId);
        String picURL = "src\\main\\resources\\rec2.png";
        
        Book1 bookP = new Book1();
        bookP.setBookDetails(bookId,bookName,author,picURL); 
        bookP.setVisible(true);
        desktop.add(bookP);
    }//GEN-LAST:event_btnRCMBook6MouseClicked

    private void btnRCMBook8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRCMBook8MouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        String bookId = "011";  // Set the actual book ID
        String bookName = DatabaseManager.getBookNameById(bookId);
        String author = DatabaseManager.getAuthorById(bookId);
        String picURL = "src\\main\\resources\\vintageRolex.png";
        
        Book1 bookP = new Book1();
        bookP.setBookDetails(bookId,bookName,author,picURL);
        bookP.setVisible(true);
        desktop.add(bookP);
    }//GEN-LAST:event_btnRCMBook8MouseClicked

    private void btnRCMBook10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRCMBook10MouseClicked
        // TODO add your handling code here:
        JDesktopPane desktop = getDesktopPane();
        
        JInternalFrame[] frames = desktop.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            desktop.remove(frame);
            }

        desktop.repaint();
        
        String bookId = "010";  // Set the actual book ID
        String bookName = DatabaseManager.getBookNameById(bookId);
        String author = DatabaseManager.getAuthorById(bookId);
        String picURL = "src\\main\\resources\\cookWKid.png";
        
        Book1 bookP = new Book1();
        bookP.setBookDetails(bookId,bookName,author,picURL);
        bookP.setVisible(true);
        desktop.add(bookP);
    }//GEN-LAST:event_btnRCMBook10MouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRCMBook1;
    private javax.swing.JButton btnRCMBook10;
    private javax.swing.JButton btnRCMBook6;
    private javax.swing.JButton btnRCMBook8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
