/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projecttemplate;

import java.awt.Dimension;
import javax.swing.*;
import javax.swing.JInternalFrame;

/**
 *
 * @author anuchatruatmakka
 */
public class MainUI extends javax.swing.JFrame {
    
    private CartFrame cartFrame;
    /**
     * Creates new form MainUI
     */
    Home homePage = new Home();
    public MainUI() {
        initComponents();
        
        //show home
        
        homePage.setVisible(true);
        jDesktopPane2.add(homePage);
        //cart
        cartFrame = new CartFrame(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHomeMenu = new javax.swing.JLabel();
        btnExploreMenu = new javax.swing.JLabel();
        btnCategoryMenu = new javax.swing.JLabel();
        btnMemberMenu = new javax.swing.JLabel();
        btnAboutusMenu = new javax.swing.JLabel();
        btnContactMenu = new javax.swing.JLabel();
        btnCartMenu = new javax.swing.JLabel();
        btnUserMenu = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1459, 800));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo_with_word.png"))); // NOI18N

        btnHomeMenu.setBackground(new java.awt.Color(255, 255, 255));
        btnHomeMenu.setText("Home");
        btnHomeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMenuMouseClicked(evt);
            }
        });

        btnExploreMenu.setText("Explore");
        btnExploreMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExploreMenuMouseClicked(evt);
            }
        });

        btnCategoryMenu.setText("Category");
        btnCategoryMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCategoryMenuMouseClicked(evt);
            }
        });

        btnMemberMenu.setText("Membership");
        btnMemberMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMemberMenuMouseClicked(evt);
            }
        });

        btnAboutusMenu.setText("About us");
        btnAboutusMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAboutusMenuMouseClicked(evt);
            }
        });

        btnContactMenu.setText("Contact");
        btnContactMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContactMenuMouseClicked(evt);
            }
        });

        btnCartMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartIcon.png"))); // NOI18N
        btnCartMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCartMenuMouseClicked(evt);
            }
        });

        btnUserMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userIcon.png"))); // NOI18N
        btnUserMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(241, 241, 241)
                .addComponent(btnHomeMenu)
                .addGap(37, 37, 37)
                .addComponent(btnExploreMenu)
                .addGap(28, 28, 28)
                .addComponent(btnCategoryMenu)
                .addGap(30, 30, 30)
                .addComponent(btnMemberMenu)
                .addGap(33, 33, 33)
                .addComponent(btnAboutusMenu)
                .addGap(35, 35, 35)
                .addComponent(btnContactMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 403, Short.MAX_VALUE)
                .addComponent(btnCartMenu)
                .addGap(37, 37, 37)
                .addComponent(btnUserMenu)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHomeMenu)
                            .addComponent(btnExploreMenu)
                            .addComponent(btnCategoryMenu)
                            .addComponent(btnMemberMenu)
                            .addComponent(btnAboutusMenu)
                            .addComponent(btnContactMenu))
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnUserMenu)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnCartMenu)
                                        .addGap(8, 8, 8)))
                                .addGap(6, 6, 6)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane2.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane2.setPreferredSize(new java.awt.Dimension(1450, 800));

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void btnHomeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMenuMouseClicked
        // TODO add your handling code here:
        JInternalFrame[] frames = jDesktopPane2.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            jDesktopPane2.remove(frame);
            }

         jDesktopPane2.repaint();
        
        
        homePage.setVisible(true);
        jDesktopPane2.add(homePage);
           
        
    }//GEN-LAST:event_btnHomeMenuMouseClicked

    private void btnContactMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContactMenuMouseClicked
        // TODO add your handling code here:
        JInternalFrame[] frames = jDesktopPane2.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            jDesktopPane2.remove(frame);
            }

         jDesktopPane2.repaint();
        
        
        Contact ct = new Contact();
        ct.setVisible(true);
        jDesktopPane2.add(ct);
        
    }//GEN-LAST:event_btnContactMenuMouseClicked

    private void btnExploreMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExploreMenuMouseClicked
        // TODO add your handling code here:
        JInternalFrame[] frames = jDesktopPane2.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            jDesktopPane2.remove(frame);
            }

         jDesktopPane2.repaint();
        
        Explore1 explore = new Explore1();
        explore.setVisible(true);
        jDesktopPane2.add(explore);
    }//GEN-LAST:event_btnExploreMenuMouseClicked

    private void btnCategoryMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategoryMenuMouseClicked
        // TODO add your handling code here:
        
        JInternalFrame[] frames = jDesktopPane2.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            jDesktopPane2.remove(frame);
            }

         jDesktopPane2.repaint();
        
        Category1 categoryFrame = new Category1();
        categoryFrame.setVisible(true);
        jDesktopPane2.add(categoryFrame);
    }//GEN-LAST:event_btnCategoryMenuMouseClicked

    private void btnMemberMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMemberMenuMouseClicked
        // TODO add your handling code here:
        JInternalFrame[] frames = jDesktopPane2.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            jDesktopPane2.remove(frame);
            }

         jDesktopPane2.repaint();
        
        MemberPage memberpage = new MemberPage();
        memberpage.setVisible(true);
        jDesktopPane2.add(memberpage);
    }//GEN-LAST:event_btnMemberMenuMouseClicked

    private void btnUserMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMenuMouseClicked
        // TODO add your handling code here:
        JInternalFrame[] frames = jDesktopPane2.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            jDesktopPane2.remove(frame);
            }

         jDesktopPane2.repaint();
         
         Profile pf = new Profile();
         pf.setVisible(true);
         jDesktopPane2.add(pf);
        
    }//GEN-LAST:event_btnUserMenuMouseClicked

    private void btnAboutusMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutusMenuMouseClicked
        // TODO add your handling code here:
        JInternalFrame[] frames = jDesktopPane2.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            jDesktopPane2.remove(frame);
            }

         jDesktopPane2.repaint();
        
        AboutUsPage aboutUsP = new AboutUsPage();
        aboutUsP.setVisible(true);
        jDesktopPane2.add(aboutUsP);
    }//GEN-LAST:event_btnAboutusMenuMouseClicked
    
    
    
    private void btnCartMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCartMenuMouseClicked
        // TODO add your handling code here:
    JInternalFrame[] frames = jDesktopPane2.getAllFrames();
    for (JInternalFrame frame : frames) {
        frame.dispose();
        jDesktopPane2.remove(frame);
    }

    jDesktopPane2.repaint();

    // Use the same instance of CartFrame
    cartFrame.setVisible(true);
    jDesktopPane2.add(cartFrame);
        
    }//GEN-LAST:event_btnCartMenuMouseClicked
    //bring home
    public void openHome(){
        
        JInternalFrame[] frames = jDesktopPane2.getAllFrames();
        for (JInternalFrame frame : frames) {
            frame.dispose();
            jDesktopPane2.remove(frame);
            
            }

         jDesktopPane2.repaint();
         
         Home homeP = new Home();
         homeP.setVisible(true);
         jDesktopPane2.add(homeP);
    }
    //get Jdesktoppane2
    public JDesktopPane getDesktopPane() {
        

        
        return jDesktopPane2;
    }
    
    public void closePayment(){
        
        
        
        homePage.setVisible(true);
        jDesktopPane2.add(homePage);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAboutusMenu;
    private javax.swing.JLabel btnCartMenu;
    private javax.swing.JLabel btnCategoryMenu;
    private javax.swing.JLabel btnContactMenu;
    private javax.swing.JLabel btnExploreMenu;
    private javax.swing.JLabel btnHomeMenu;
    private javax.swing.JLabel btnMemberMenu;
    private javax.swing.JLabel btnUserMenu;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
