/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.projecttemplate;

import java.sql.*;

/**
 *
 * @author Lenovo
 */
public class MemberPage extends javax.swing.JInternalFrame {

    /**
     * Creates new form MemberPage
     */
    public MemberPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rdoBtnPlanA = new javax.swing.JRadioButton();
        rdoBtnPlanB = new javax.swing.JRadioButton();
        rdoBtnPlanC = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBecomeMember = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1440, 800));

        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 800));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Membership");

        buttonGroup1.add(rdoBtnPlanA);
        rdoBtnPlanA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rdoBtnPlanA.setText("Plan A");

        buttonGroup1.add(rdoBtnPlanB);
        rdoBtnPlanB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rdoBtnPlanB.setText("Plan B");

        buttonGroup1.add(rdoBtnPlanC);
        rdoBtnPlanC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rdoBtnPlanC.setText("Plan C");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("10% discount ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("15% discount ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("20% discount ");

        btnBecomeMember.setText("Become member");
        btnBecomeMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBecomeMemberMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(613, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(611, 611, 611))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rdoBtnPlanB)
                                .addComponent(rdoBtnPlanC)
                                .addComponent(rdoBtnPlanA)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)))))
                        .addGap(645, 645, 645))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBecomeMember)
                        .addGap(637, 637, 637))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addComponent(rdoBtnPlanA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(62, 62, 62)
                .addComponent(rdoBtnPlanB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(82, 82, 82)
                .addComponent(rdoBtnPlanC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(120, 120, 120)
                .addComponent(btnBecomeMember)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1402, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBecomeMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBecomeMemberMouseClicked
        // TODO add your handling code here:
        
        // Get the selected membership plan
        String selectedPlan = getSelectedPlan();

        // Store the selected plan in the database
        storeMembershipPlan(selectedPlan);
    }//GEN-LAST:event_btnBecomeMemberMouseClicked
    
    private String getSelectedPlan() {
        if (rdoBtnPlanA.isSelected()) {
            return "Plan A";
        } else if (rdoBtnPlanB.isSelected()) {
            return "Plan B";
        } else if (rdoBtnPlanC.isSelected()) {
            return "Plan C";
        } else {
            // Handle the case where no plan is selected
            return "";
        }
    }
    
    private void storeMembershipPlan(String selectedPlan) {
        // Database connection parameters
        String url = "jdbc:sqlite:src\\main\\resources\\Account.db";

        try (Connection connection = DriverManager.getConnection(url);
             PreparedStatement preparedStatement = connection.prepareStatement("UPDATE accountList SET member = ? WHERE username = ?")) {

            // Set the selected plan as a parameter
            preparedStatement.setString(1, selectedPlan);
            preparedStatement.setString(2, Globalinfo.username);

            // Execute the update query
            preparedStatement.executeUpdate();

        } catch (SQLException e) {
            // Handle database-related exceptions
            e.printStackTrace();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBecomeMember;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdoBtnPlanA;
    private javax.swing.JRadioButton rdoBtnPlanB;
    private javax.swing.JRadioButton rdoBtnPlanC;
    // End of variables declaration//GEN-END:variables
}
